package com.osrstcgbattles.engine;

public enum RejectionReason
{
	MATCH_COMPLETE,
	COMMAND_NOT_ALLOWED_IN_PHASE,
	NOT_ACTIVE_PLAYER,
	MULLIGAN_LIMIT_REACHED,
	DRAW_PILE_EMPTY,
	PLAYER_ALREADY_PASSED,
	CARD_NOT_IN_HAND,
	NOT_ENOUGH_MANA,
	BATTLEFIELD_FULL,
	ATTACKER_NOT_FOUND,
	ATTACKER_NOT_ALLIED,
	ATTACKER_NOT_READY,
	HERO_PROTECTED,
	ROW_NOT_ALLOWED,
	ROW_FULL,
	TARGET_REQUIRED,
	TARGET_NOT_ALLOWED,
	TARGET_NOT_FOUND,
	TARGET_NOT_ALLIED,
	TARGET_NOT_ENEMY,
	UNSUPPORTED_COMMAND
}
