package com.osrstcgbattles.online;

/** Version-one client/server message vocabulary. */
public enum OnlineMessageType
{
	HELLO,
	WELCOME,
	ERROR,
	AUTH_BEGIN,
	AUTH_CHALLENGE,
	AUTH_RESPONSE,
	AUTHENTICATED,
	LOBBY_CREATE,
	LOBBY_CREATED,
	LOBBY_JOIN,
	LOBBY_JOINED,
	LOBBY_LEAVE,
	MATCH_FOUND,
	MATCH_ACK,
	MATCH_ABANDON,
	MATCH_COMMAND,
	MATCH_STATE,
	MATCH_REJECTED,
	MATCH_COMPLETE,
	MATCH_ABORTED,
	RESUME,
	QUEUE_JOIN,
	QUEUE_LEAVE,
	QUEUE_STATUS,
	RANKED_QUEUE_JOIN,
	RANKED_QUEUE_LEAVE,
	RANKED_QUEUE_STATUS,
	RATING_UPDATE
}
